//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wholesale_Marketplace.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dialog_dispute
    {
        public Dialog_dispute()
        {
            this.Messages = new HashSet<Message>();
        }
    
        public int DisputeID { get; set; }
        public int BuyerID { get; set; }
        public Nullable<int> SellerID { get; set; }
        public Nullable<int> AgentID { get; set; }
        public System.DateTime Open_date { get; set; }
        public bool IsDispute { get; set; }
        public Nullable<System.DateTime> Close_date { get; set; }
        public string Resolution_text { get; set; }
        public Nullable<int> OrderID { get; set; }
        public bool HasNewMessages { get; set; }
        public Nullable<int> ItemID { get; set; }
        public Nullable<double> RefundValue { get; set; }
        public Nullable<bool> SellerAgree { get; set; }
        public Nullable<bool> BuyerAgree { get; set; }
        public Nullable<int> DisputeStateID { get; set; }
    
        public virtual Buyer Buyer { get; set; }
        public virtual ICollection<Message> Messages { get; set; }
        public virtual Support_agent Support_agent { get; set; }
        public virtual Seller Seller { get; set; }
        public virtual Order Order { get; set; }
        public virtual Item Item { get; set; }
        public virtual DisputeState DisputeState { get; set; }
    }
}
