//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wholesale_Marketplace.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item_category
    {
        public Item_category()
        {
            this.Item = new HashSet<Item>();
        }
    
        public int Category_number { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Item> Item { get; set; }
    }
}
