//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wholesale_Marketplace.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Picture
    {
        public int PictureID { get; set; }
        public Nullable<int> ItemID { get; set; }
        public Nullable<int> MessageID { get; set; }
        public string Description { get; set; }
        public byte[] Image { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual Message Message { get; set; }
    }
}
