//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wholesale_Marketplace.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Picture
    {
        public int Picture_number { get; set; }
        public int Item_number { get; set; }
        public Nullable<int> Message_number { get; set; }
        public string Description { get; set; }
        public byte[] Picture1 { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual Message Message { get; set; }
    }
}
