//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wholesale_Marketplace.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Picture
    {
        public int PictureID { get; set; }
        public Nullable<int> ItemID { get; set; }
        public Nullable<int> MessageID { get; set; }
        public string Description { get; set; }
        public byte[] Image { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual Message Message { get; set; }
    }
}
