//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wholesale_Marketplace.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Store
    {
        public Store()
        {
            this.Items = new HashSet<Item>();
            this.Sellers = new HashSet<Seller>();
        }
    
        public int StoreID { get; set; }
        public string Name { get; set; }
        public int Rating { get; set; }
        public int Orders_count { get; set; }
        public int Positive_marks { get; set; }
        public int Negative_marks { get; set; }
        public System.DateTime Created_date { get; set; }
        public string Description { get; set; }
        public int Owner_sellerID { get; set; }
    
        public virtual ICollection<Item> Items { get; set; }
        public virtual ICollection<Seller> Sellers { get; set; }
    }
}
