//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wholesale_Marketplace.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Support_agent
    {
        public Support_agent()
        {
            this.Dialog_dispute = new HashSet<Dialog_dispute>();
            this.Order = new HashSet<Order>();
        }
    
        public int Agent_number { get; set; }
        public string Name { get; set; }
        public string Login { get; set; }
        public string Pass { get; set; }
        public string Email { get; set; }
        public Nullable<int> Disputes_count { get; set; }
        public Nullable<System.DateTime> Registration_date { get; set; }
    
        public virtual ICollection<Dialog_dispute> Dialog_dispute { get; set; }
        public virtual ICollection<Order> Order { get; set; }
    }
}
