//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wholesale_Marketplace.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("WMDB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Buyer> Buyer { get; set; }
        public virtual DbSet<Dialog_dispute> Dialog_dispute { get; set; }
        public virtual DbSet<Dispute_status> Dispute_status { get; set; }
        public virtual DbSet<Item> Item { get; set; }
        public virtual DbSet<Item_category> Item_category { get; set; }
        public virtual DbSet<Message> Message { get; set; }
        public virtual DbSet<Order> Order { get; set; }
        public virtual DbSet<Order_status> Order_status { get; set; }
        public virtual DbSet<Picture> Picture { get; set; }
        public virtual DbSet<Seller> Seller { get; set; }
        public virtual DbSet<Shipping_type> Shipping_type { get; set; }
        public virtual DbSet<Store> Store { get; set; }
        public virtual DbSet<Support_agent> Support_agent { get; set; }
    }
}
