//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wholesale_Marketplace.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dialog_dispute
    {
        public Dialog_dispute()
        {
            this.Message = new HashSet<Message>();
            this.Order1 = new HashSet<Order>();
        }
    
        public int Dispute_number { get; set; }
        public int Buyer_number { get; set; }
        public int Seller_number { get; set; }
        public int Agent_number { get; set; }
        public int Order_number { get; set; }
        public Nullable<int> Dispute_status_number { get; set; }
        public Nullable<System.DateTime> Open_date { get; set; }
        public Nullable<bool> IsDispute { get; set; }
        public Nullable<System.DateTime> Close_date { get; set; }
        public string Resolution_text { get; set; }
    
        public virtual Buyer Buyer { get; set; }
        public virtual Order Order { get; set; }
        public virtual Dispute_status Dispute_status { get; set; }
        public virtual Support_agent Support_agent { get; set; }
        public virtual Seller Seller { get; set; }
        public virtual ICollection<Message> Message { get; set; }
        public virtual ICollection<Order> Order1 { get; set; }
    }
}
