//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wholesale_Marketplace.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dialog_dispute
    {
        public Dialog_dispute()
        {
            this.Messages = new HashSet<Message>();
            this.Orders = new HashSet<Order>();
        }
    
        public int DisputeID { get; set; }
        public int BuyerID { get; set; }
        public int SellerID { get; set; }
        public int AgentID { get; set; }
        public int Dispute_statusID { get; set; }
        public System.DateTime Open_date { get; set; }
        public bool IsDispute { get; set; }
        public Nullable<System.DateTime> Close_date { get; set; }
        public string Resolution_text { get; set; }
    
        public virtual Buyer Buyer { get; set; }
        public virtual Dispute_status Dispute_status { get; set; }
        public virtual Support_agent Support_agent { get; set; }
        public virtual Seller Seller { get; set; }
        public virtual ICollection<Message> Messages { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
    }
}
