//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wholesale_Marketplace.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dispute_status
    {
        public Dispute_status()
        {
            this.Dialog_dispute = new HashSet<Dialog_dispute>();
        }
    
        public int Dispute_statusID { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Dialog_dispute> Dialog_dispute { get; set; }
    }
}
