//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wholesale_Marketplace.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public Item()
        {
            this.Orders = new HashSet<Order>();
            this.Pictures = new HashSet<Picture>();
            this.Dialog_dispute = new HashSet<Dialog_dispute>();
        }
    
        public int ItemID { get; set; }
        public int StoreID { get; set; }
        public int CategoryID { get; set; }
        public string Name { get; set; }
        public double Price { get; set; }
        public string Description { get; set; }
        public int Orders_count { get; set; }
        public int Minimum_order { get; set; }
        public System.DateTime Open_date { get; set; }
        public Nullable<System.DateTime> Close_date { get; set; }
        public int Left_goods_count { get; set; }
        public int Marks_count { get; set; }
        public double Average_mark { get; set; }
    
        public virtual Store Store { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
        public virtual ICollection<Picture> Pictures { get; set; }
        public virtual Item_category Item_category { get; set; }
        public virtual ICollection<Dialog_dispute> Dialog_dispute { get; set; }
    }
}
