//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wholesale_Marketplace.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public Message()
        {
            this.Pictures = new HashSet<Picture>();
        }
    
        public int MessageID { get; set; }
        public int DisputeID { get; set; }
        public string Text { get; set; }
        public System.DateTime Post_date { get; set; }
        public int UserID { get; set; }
    
        public virtual Dialog_dispute Dialog_dispute { get; set; }
        public virtual ICollection<Picture> Pictures { get; set; }
        public virtual User User { get; set; }
    }
}
