//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wholesale_Marketplace.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int OrderID { get; set; }
        public int AgentID { get; set; }
        public int BuyerID { get; set; }
        public int ItemID { get; set; }
        public int DisputeID { get; set; }
        public int ShippingID { get; set; }
        public int Order_statusID { get; set; }
        public double Total_price { get; set; }
        public System.DateTime Open_date { get; set; }
        public Nullable<System.DateTime> Close_date { get; set; }
        public int Amount { get; set; }
        public Nullable<int> Mark { get; set; }
        public string Review_text { get; set; }
        public string Address { get; set; }
        public string ForSellerInfo { get; set; }
        public string ForBuyerInfo { get; set; }
        public int SellerID { get; set; }
    
        public virtual Buyer Buyer { get; set; }
        public virtual Dialog_dispute Dialog_dispute { get; set; }
        public virtual Item Item { get; set; }
        public virtual Support_agent Support_agent { get; set; }
        public virtual Shipping_type Shipping_type { get; set; }
        public virtual Order_status Order_status { get; set; }
        public virtual Seller Seller { get; set; }
    }
}
