//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wholesale_Marketplace.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Store
    {
        public Store()
        {
            this.Item = new HashSet<Item>();
            this.Seller = new HashSet<Seller>();
        }
    
        public int Store_number { get; set; }
        public string Name { get; set; }
        public Nullable<int> Rating { get; set; }
        public Nullable<int> Orders_count { get; set; }
        public Nullable<int> Positive_marks { get; set; }
        public Nullable<int> Negative_marks { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public string Description { get; set; }
        public Nullable<int> Owner_seller_number { get; set; }
    
        public virtual ICollection<Item> Item { get; set; }
        public virtual ICollection<Seller> Seller { get; set; }
    }
}
