//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wholesale_Marketplace.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Buyers = new HashSet<Buyer>();
            this.Sellers = new HashSet<Seller>();
            this.Support_agent = new HashSet<Support_agent>();
        }
    
        public int UserID { get; set; }
        public int RoleID { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
    
        public virtual ICollection<Buyer> Buyers { get; set; }
        public virtual Role Role { get; set; }
        public virtual ICollection<Seller> Sellers { get; set; }
        public virtual ICollection<Support_agent> Support_agent { get; set; }
    }
}
