//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wholesale_Marketplace.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WMDB : DbContext
    {
        public WMDB()
            : base("name=WMDB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Buyer> Buyers { get; set; }
        public virtual DbSet<Dialog_dispute> Dialog_dispute { get; set; }
        public virtual DbSet<Dispute_status> Dispute_status { get; set; }
        public virtual DbSet<Item> Items { get; set; }
        public virtual DbSet<Item_category> Item_category { get; set; }
        public virtual DbSet<Message> Messages { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<Order_status> Order_status { get; set; }
        public virtual DbSet<Picture> Pictures { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Seller> Sellers { get; set; }
        public virtual DbSet<Shipping_type> Shipping_type { get; set; }
        public virtual DbSet<Store> Stores { get; set; }
        public virtual DbSet<Support_agent> Support_agent { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
